target-version = "py39" # python3.9
extend-exclude = [
  "BasicPlotting",
  "count18Data",
  "SFPUtest",
]
line-length = 120

[lint]
extend-select = [
  "C4",   # comprehensions
  "B",    # find bug-prone patterns
  "ARG",  # unused arguments
  "PL",   # Pylint codes
]
ignore = [
  "PLR",      # design-related Pylint codes
  "E402",     # ignore module imports not at the top
  "PLC0415",  # ^ ^ ^
  "PLW2901",  # ignore overwrites of loop variable
  "E731",     # ignore assignments to lambda
  "PLW0603",  # ignore global variables (to avoid major rewrite)
]
